spring:
  datasource:
    # Sửa serverTimezone thành Asia/Ho_Chi_Minh
    url: jdbc:mysql://localhost:3306/hospital_chatbot?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    hikari:
      pool-name: TestHikariCP

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.enable_lazy_load_no_trans: true
      # Thêm dòng này để Hibernate hiểu múi giờ khi lưu/đọc
      hibernate.jdbc.time_zone: Asia/Ho_Chi_Minh

  # Cấu hình Jackson để format JSON trả về đúng múi giờ VN
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd HH:mm:ss

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8080

jwt:
  secretKey: "unRgKLqmtvb/9icGgNImphNA9WMs5qCVkrQtH4sKV2w="
  expiration: 86400

file:
  upload-dir: uploads
  specialty-dir: specialties
  doctor-dir: doctors